version: "3.3"
services:
  frontend:
    image: 'finalangularapp'
    container_name: frontend
    ports:
      - '8081:4200'
    depends_on:
      - restapi
  
  restapi:
    image: 'finalapi'
    container_name: restapi
    ports:
      - '5555:5555'
